Add bluetooth actions queue for Android
sogilis/react-native-bluetooth-manager pull request #6
Opened 2017-02-06 16:28 UTC by hamadr

Bluetooth actions are now executed one at a time allowing
proper communication.

2017-02-06 16:59 UTC, sdenier requested changes
C'est ok mais ça serait pas mal de faire 2 petites méthodes pour add/done action

2017-02-06 16:59 UTC, sdenier commented on android/src/main/java/com/sogilis/ReactNativeBluetooth/ReactNativeBluetoothModule.java
> +        }.start();
Ca marchait comment avant ?

2017-02-06 16:59 UTC, sdenier commented on android/src/main/java/com/sogilis/ReactNativeBluetooth/ReactNativeBluetoothModule.java
> +                    bluetoothEventLoopTick();
Extract method `bluetoothEventLoopActionDone()`

2017-02-06 16:59 UTC, sdenier commented on android/src/main/java/com/sogilis/ReactNativeBluetooth/ReactNativeBluetoothModule.java
> +        bluetoothEventLoopTick();
Extract method `bluetoothEventLoopAddAction(writeAction)`

2017-02-07 09:23 UTC, hamadr commented on android/src/main/java/com/sogilis/ReactNativeBluetooth/ReactNativeBluetoothModule.java
> +        }.start();
Le `this.run();` de `BluetoothAction` était appelé dans le constructeur.

2017-02-07 09:49 UTC, sdenier commented on android/src/main/java/com/sogilis/ReactNativeBluetooth/ReactNativeBluetoothModule.java
> +import java.util.concurrent.ConcurrentLinkedQueue;
import inutile ?

2017-02-07 09:50 UTC, sdenier approved these changes

2017-02-07 09:59 UTC, merged